/**
 * OpenAI proxy, the Responses streaming endpoint (/v1/responses) — the same shape as
 * ai.js's `callGemini` and anthropic.js's `callAnthropicChat`: the app
 * never holds `OPENAI_API_KEY`, only this Worker does.
 *
 * Model IDs are deliberately NOT hardcoded here. OpenAI's current
 * flagship/mid-tier model names were not confirmed at the time this file
 * was written, so the two "openai-mid"/"openai-flagship" logical models in
 * ai.js's `PLAN_MODELS` are resolved to real model ids via
 * `env.OPENAI_MID_MODEL` / `env.OPENAI_FLAGSHIP_MODEL` instead of a
 * constant in this file. Before enabling either logical model, check
 * OpenAI's current model documentation for the right id and set it with
 * `wrangler secret put OPENAI_MID_MODEL` (or as a plain `vars` entry in
 * wrangler.jsonc, since a model name by itself isn't sensitive — only
 * `OPENAI_API_KEY` needs to stay a secret).
 */

const API_URL = "https://api.openai.com/v1/responses";
const MAX_OUTPUT_TOKENS = 4096;

/** A user turn's content parts: its text, plus any images attached to it. */
function userContent(turn, images) {
  const parts = [{ type: "input_text", text: String(turn.text ?? "") }];
  for (const image of images) {
    parts.push({ type: "input_image", image_url: `data:image/png;base64,${image}`, detail: "auto" });
  }
  return parts;
}

/**
 * Builds the Responses API request body. Exported so tests can pin its shape.
 *
 * `store: false` keeps the conversation off OpenAI's side (ADR-0002): the
 * whole history is sent every turn, exactly as before, and
 * `previous_response_id` is never used. The system prompt goes in
 * `instructions`; assistant turns are plain strings (they were generated by
 * the model earlier), user turns are typed parts so images can ride along.
 */
export function buildResponsesBody({ model, systemInstruction, turns, images = [] }) {
  const lastIndex = turns.length - 1;
  return {
    model,
    instructions: systemInstruction,
    input: turns.map((turn, index) =>
      turn.role === "assistant"
        ? { role: "assistant", content: String(turn.text ?? "") }
        : { role: "user", content: userContent(turn, index === lastIndex ? images : []) },
    ),
    max_output_tokens: MAX_OUTPUT_TOKENS,
    stream: true,
    store: false,
  };
}

/**
 * `turns` is the same provider-agnostic shape ai.js's chat handler already
 * builds for Gemini (`{ role: "user" | "assistant", text }`). `images`
 * (already-validated PNG base64 strings) are attached to the last turn
 * only, matching how the app's own screenshot-attach flow works.
 *
 * `apiKey` defaults to this Worker's own `OPENAI_API_KEY`; it is a parameter
 * so a per-user token can be passed here later without touching the body.
 */
export async function callOpenAIChat(env, { model, systemInstruction, turns, images = [], apiKey = env.OPENAI_API_KEY }) {
  if (!apiKey) throw new Error("OPENAI_API_KEY is not configured on this Worker.");

  return fetch(API_URL, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(buildResponsesBody({ model, systemInstruction, turns, images })),
  });
}

/**
 * Pulls the incremental text out of one parsed Responses SSE event. Only
 * `response.output_text.delta` carries text; every other event (created,
 * output_item.*, completed, ...) yields "". Responses streams have no
 * terminal `[DONE]` line — ai.js's pump ends when the body ends.
 */
export function extractDeltaText(event) {
  if (event?.type !== "response.output_text.delta") return "";
  return typeof event.delta === "string" ? event.delta : "";
}
